/**
 * A real mountain, as two tables.
 *
 * GENERATED BY `node tools/bake-run.mjs` — edit that, not this.
 *
 * Sampled from Chamonix–Argentière, Mont Blanc massif via the public AWS terrarium elevation tiles at
 * zoom 13 (about 13 m per pixel on the ground). A steepest-descent
 * walk from the 3141 m summit was projected onto the chord between its
 * endpoints, giving distance downhill and offset across — the game's own z and
 * x. The descent drops 530 m over 3000 m, a mean grade of 0.177.
 *
 * These are the only two things taken from the real world, and both are
 * low-frequency by necessity: 30 m elevation postings cannot describe a 16 m
 * piste, let alone a kicker on it. Everything the rider actually touches is
 * still the analytic height field in `Course.js`. See the header of
 * `tools/bake-run.mjs` for the full reasoning.
 *
 * Samples are every 25 m of z, starting at z = 0.
 */

/** Metres between consecutive samples in both tables below. */
export const ELEVATION_STEP = 25;

/**
 * Steepness down the fall line — metres of drop per metre of z, the same units
 * as `grade.base`. Range 0.107 to 0.315.
 */
export const ELEVATION_GRADE = [
  0.2584, 0.2697, 0.2911, 0.3087, 0.3153, 0.2992, 0.2600, 0.2155, 0.1829, 0.1649,
  0.1542, 0.1449, 0.1369, 0.1325, 0.1343, 0.1437, 0.1614, 0.1845, 0.2046, 0.2143,
  0.2102, 0.1943, 0.1719, 0.1512, 0.1395, 0.1411, 0.1554, 0.1758, 0.1912, 0.1927,
  0.1798, 0.1572, 0.1342, 0.1197, 0.1155, 0.1205, 0.1317, 0.1463, 0.1616, 0.1737,
  0.1763, 0.1667, 0.1461, 0.1239, 0.1105, 0.1068, 0.1099, 0.1150, 0.1191, 0.1231,
  0.1300, 0.1396, 0.1501, 0.1580, 0.1595, 0.1558, 0.1491, 0.1418, 0.1351, 0.1286,
  0.1244, 0.1234, 0.1245, 0.1267, 0.1303, 0.1372, 0.1491, 0.1647, 0.1788, 0.1860,
  0.1846, 0.1765, 0.1659, 0.1569, 0.1516, 0.1489, 0.1457, 0.1386, 0.1271, 0.1155,
  0.1119, 0.1233, 0.1521, 0.1926, 0.2347, 0.2684, 0.2873, 0.2899, 0.2789, 0.2597,
  0.2387, 0.2221, 0.2139, 0.2139, 0.2186, 0.2238, 0.2260, 0.2235, 0.2179, 0.2106,
  0.2013, 0.1905, 0.1783, 0.1657, 0.1548, 0.1484, 0.1496, 0.1598, 0.1774, 0.1968,
  0.2123, 0.2204, 0.2209, 0.2170, 0.2119, 0.2076, 0.2034, 0.1997, 0.1953, 0.1904,
  0.1885,
];

/**
 * How far the real fall line sits left or right of the straight chord, in
 * metres. Mean removed, so the run stays centred on x = 0 like every other
 * preset. Reaches 146 m off the chord at its widest.
 */
export const ELEVATION_WANDER = [
  -140.84, -114.14, -88.32, -63.95, -41.40, -20.95, -2.73, 13.15, 26.61, 37.64,
  46.13, 52.26, 56.02, 57.59, 57.12, 54.84, 50.98, 45.80, 39.60, 32.69,
  25.42, 18.13, 11.12, 4.64, -1.11, -6.00, -9.86, -12.70, -14.41, -15.03,
  -14.51, -12.89, -10.10, -6.20, -1.14, 5.04, 12.31, 20.59, 29.71, 39.48,
  49.60, 59.73, 69.50, 78.51, 86.46, 93.02, 98.07, 101.59, 103.64, 104.43,
  104.16, 103.09, 101.46, 99.48, 97.35, 95.20, 93.14, 91.24, 89.56, 88.13,
  87.01, 86.20, 85.74, 85.61, 85.78, 86.20, 86.83, 87.58, 88.37, 89.07,
  89.60, 89.83, 89.64, 88.94, 87.59, 85.52, 82.59, 78.75, 73.86, 67.91,
  60.80, 52.59, 43.32, 33.07, 22.00, 10.29, -1.90, -14.39, -27.01, -39.60,
  -52.02, -64.13, -75.82, -86.95, -97.44, -107.14, -115.96, -123.82, -130.59, -136.24,
  -140.68, -143.86, -145.79, -146.48, -146.05, -144.61, -142.36, -139.51, -136.30, -132.99,
  -129.80, -126.98, -124.68, -123.10, -122.35, -122.58, -123.79, -126.06, -129.33, -133.61,
  -138.74,
];
